version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    container_name: db

  wordpress:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "8000:80"
    volumes:
     - plugins:/var/www/html/wp-content/plugins
     - themes:/var/www/html/wp-content/themes
     - ../:/var/www/html/wp-content/plugins/tapestry-wp
    container_name: wp
    
  app:
    depends_on:
      - db
    build:
      context: ../templates/vue
      target: 'develop-stage'
    restart: always
    ports:
      - '8080:8080'
    volumes: 
      - ../templates/vue:/app
      - node_modules:/app/node_modules
    command: npm run dev:container
    container_name: app
    
  e2e:
    image: "cypress/included:4.9.0"
    shm_size: 2GB
    depends_on: 
      - dev
      - wordpress
    environment:
      - CYPRESS_baseUrl=http://localhost:8000
    network_mode: host
    volumes: 
      - ../templates/e2e:/e2e
    working_dir: /e2e
    container_name: e2e
    entrypoint: tail -f /dev/null

volumes:
    db_data:
    node_modules:
    plugins:
    themes: